apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen2-apr29-1
  janus-idp.io/tekton: codegen2-apr29-1
  backstage.io/kubernetes-id: codegen2-apr29-1
  backstage.io/kubernetes-namespace: codegen2-apr29-1
  app.kubernetes.io/part-of: codegen2-apr29-1
resources:
  - application-dev.yaml